# suppress inspection "UnusedProperty" for whole file
logging.level.root=INFO
logging.file.name=kraken-bot.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
