package com.gemini.krakenbot.view.util

object ViewText {
    const val APP_TITLE = "Kraken Rebalancer"
    const val SETTINGS_TITLE = "Settings"
    const val PORTFOLIO_ALLOCATION = "Portfolio Allocation (Top Assets)"
    const val ASSET_PERFORMANCE = "Asset Performance"
    const val TOTAL_PORTFOLIO = "Total Portfolio"
    const val CASH_USD = "Cash (USD)"
    const val CRYPTO_ASSETS = "Crypto Assets"
    const val RECENT_ACTIVITY = "Recent Activity"
    const val NO_TRADING_HISTORY = "No trading history available."
    const val NO_TRADES_EXECUTED = "No trades executed (Cycle complete)"
    const val CONNECTING = "Connecting to KrakenRebalancer..."
    const val WAITING_FIRST_CYCLE = "Waiting for first rebalance cycle"
    const val REBALANCER_RUNNING =
        "The rebalancer is running. Portfolio data will appear here after the first cycle completes."
    const val GLOBAL_PARAMETERS = "Global Parameters"
    const val LOOP_INTERVAL = "Loop Interval (Seconds)"
    const val DEVIATION_TRIGGER = "Deviation Trigger (%)"
    const val DUST_THRESHOLD = "Dust Threshold ($)"
    const val FIAT_MAX_DRAWDOWN = "Fiat Max Drawdown (%)"
    const val FIAT_DEPLOYMENT_EXPONENT = "Fiat Deployment Exponent"
    const val DRY_RUN_MODE = "Dry Run Mode (Safe)"
    const val SIMULATION_MODE = "Simulation Mode (Kraken Emulator)"
    const val TARGET_ALLOCATIONS = "Target Allocations"
    const val ADD_ASSET = "Add Asset"
    const val SAVE_CONFIGURATION = "Save Configuration"

    // Status / Labels
    const val LIVE = "LIVE"
    const val DELAYED = "DELAYED"
    const val DATA_AGE = "Data Age"
    const val NO_USD_DATA = "No USD Data"
    const val DRAWDOWN_PREFIX = "Drawdown: "
    const val TARGET_PREFIX = "Target: "
    const val BASE_PREFIX = "Base: "
    const val DEV_PREFIX = "Dev: "
    const val ASSETS_SUFFIX = " Assets"
    const val REMOVE = "Remove"
    const val NEW_SYMBOL_PLACEHOLDER = "New Symbol (e.g. DOT)"
    const val TOTAL_INITIAL = "Total: 0.00%"
    const val PLACEHOLDER_DASHES = "--"
    const val PRICE_NOT_FOUND_PREFIX = "Price not found for "

    // Table Headers
    const val HEADER_ASSET = "Asset"
    const val HEADER_PRICE = "Price"
    const val HEADER_VALUE = "Value"
    const val HEADER_TARGET_PCT = "Target %"
    const val HEADER_CURRENT_PCT = "Current %"
    const val HEADER_DEV_PCT = "Dev %"
    const val HEADER_TIME = "Time"
    const val HEADER_ACTION = "Action"

    // History page
    const val HISTORY_TITLE = "History"
    const val HISTORY_PORTFOLIO_VALUE = "Portfolio Value Over Time"
    const val HISTORY_ASSET_HOLDINGS = "Asset Holdings Over Time"
    const val HISTORY_ALLOCATION_DRIFT = "Allocation Drift Over Time"
    const val HISTORY_CUMULATIVE_PL = "Cumulative Realized P&L"
    const val HISTORY_TRADE_LOG = "Trade History"
    const val HISTORY_ALL_TIME_HIGH = "All-Time High"
    const val HISTORY_TOTAL_TRADES = "Total Trades"
    const val HISTORY_TOTAL_VOLUME = "Total Volume Traded"
    const val HISTORY_TOTAL_FEES = "Total Fees Paid"
    const val HISTORY_NO_DATA = "No historical data available yet. Data will appear after the first rebalance cycle."
    const val SHOW_DRY_RUN_TRADES = "Show Dry Run Trades"
    const val SYNCHRONIZING_TRADE_HISTORY = "Synchronizing Kraken Trade History..."
    const val INITIAL_SYNC_PROGRESS = "0 / 0 (0%)"
    const val LABEL_ALL = "All"

    // Navigation
    const val NAV_DASHBOARD = "Dashboard"
    const val NAV_HISTORY = "History"
    const val NAV_SETTINGS = "Settings"

    // History trade table headers
    const val HEADER_PAIR = "Pair"
    const val HEADER_SIDE = "Side"
    const val HEADER_VOLUME = "Volume"
    const val HEADER_USD_AMOUNT = "USD Amount"
    const val HEADER_STATUS = "Status"
}
